# build-godot32-ssse3-gcc.yml
name: Build Godot32 (SSSE3, GCC)
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/_build-godot32.yml
    with:
      use_ssse3: true
      artifact_name: godot32-ssse3-gcc
