# build-godot32-llvm.yml
name: Build Godot32 (LLVM)
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/_build-godot32.yml
    with:
      use_llvm: true
      artifact_name: godot32-llvm
